/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package decorClass;

import Main.MainTask;
import MainSWM.AllJFrame;
import java.awt.Color;
import javaant.TaskData;
import javax.swing.*;

/**
 *
 * @author DELL
 */
public class EditTitleFrame extends JFrame {
    private TaskData data;
    private TaskPattern tp;
    private AllJFrame allj;
    /**
     * Creates new form EditTitleFrame
     */
    
    
    public EditTitleFrame(AllJFrame allj, TaskData data, TaskPattern tp) {
        this.allj = allj;
        this.data = data;
        this.tp = tp;
        System.out.println("ETF : task no. "+tp.getTaskOrder());
        initComponents();
        EditorField.setBackground(new Color(207,224,193));
        
        setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EditorPanel = new decorClass.RoundedPanel();
        EditorLabel = new javax.swing.JLabel();
        fieldpanel = new decorClass.RoundedPanel();
        EditorField = new javax.swing.JTextField();
        DoneButton = new decorClass.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(142, 211, 170));

        EditorPanel.setBackground(new java.awt.Color(129, 169, 142));

        EditorLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        EditorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EditorLabel.setText("Edit Your Tiltle");

        javax.swing.GroupLayout EditorPanelLayout = new javax.swing.GroupLayout(EditorPanel);
        EditorPanel.setLayout(EditorPanelLayout);
        EditorPanelLayout.setHorizontalGroup(
            EditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );
        EditorPanelLayout.setVerticalGroup(
            EditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EditorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        fieldpanel.setBackground(new java.awt.Color(207, 224, 193));

        EditorField.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        EditorField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EditorField.setBorder(null);
        EditorField.setCaretColor(new java.awt.Color(129, 186, 113));
        EditorField.setDisabledTextColor(null);
        EditorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditorFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fieldpanelLayout = new javax.swing.GroupLayout(fieldpanel);
        fieldpanel.setLayout(fieldpanelLayout);
        fieldpanelLayout.setHorizontalGroup(
            fieldpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fieldpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditorField, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );
        fieldpanelLayout.setVerticalGroup(
            fieldpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DoneButton.setBackground(new java.awt.Color(197, 87, 98));
        DoneButton.setForeground(new java.awt.Color(78, 33, 38));
        DoneButton.setText("Done");
        DoneButton.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(DoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fieldpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        String textEditor = EditorField.getText();
        data.settaskname(textEditor);
        System.out.println(textEditor);
        //tp.setTaskTitle(textEditor);
        //tp.setTaskTitle(data.gettaskname());
        allj.addTaskdatalist(tp.getTaskOrder()-1, data);
        allj.recreateTask();
        this.dispose();
    }//GEN-LAST:event_DoneButtonActionPerformed

    private void EditorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditorFieldActionPerformed

    }//GEN-LAST:event_EditorFieldActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private decorClass.RoundedButton DoneButton;
    private javax.swing.JTextField EditorField;
    private javax.swing.JLabel EditorLabel;
    private decorClass.RoundedPanel EditorPanel;
    private decorClass.RoundedPanel fieldpanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
