
package decorClass;
//import decorClass.;
import MainSWM.AllJFrame;
import MainSWM.EditDelete;
import java.awt.event.*;
import javaant.TaskData;
//import Main.*;
/**
 *
 * @author DELL
 */
public class TaskPattern extends javax.swing.JPanel {
    private int taskOrder;
    private String taskname;
    private int state;
    private TaskData data;
    private AllJFrame allj;
//    private String status;
    /**
     * Creates new form TaskPattern
     * @param allj
     * @param taskOrder
     */
    public TaskPattern(AllJFrame allj, int taskOrder, TaskData data) {
        //state = 0;
        //data = new TaskData();
        this.allj = allj;
        this.data = data;
        this.taskOrder = taskOrder;
        this.taskname = data.gettaskname();
        this.state = data.getstate();
        initComponents();
    }
    public int getTaskOrder() {
        return taskOrder;
    }
    public TaskData getdata() {
        return data;
    }
    public void setTaskTitle(String taskname){
        //data.settaskname(taskname);
        taskTitle.setText(taskname);
    }
    public void resetTitleName() {
        taskTitle.setText(data.gettaskname());
    }
    public String getTitleName(){
        return taskname;
    }
    
    public void setState(String status){
        if (status.equals("available")) {
            data.setstate(1);
        }
        else if (status.equals("not available")) {
            data.setstate(0);

        }
    }
    public int getState(){
        return state;
    }
    
    public void openEDframe(){
        EditDelete buttonFrame = new EditDelete(allj, data, this);
        buttonFrame.setVisible(true);
        data.setstate("available");
        state = data.getstate();
        System.out.println(state + " : Edit or Delete me ?");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roundedPanel3 = new decorClass.RoundedPanel();
        taskTitle = new javax.swing.JCheckBox();
        buttEditor = new decorClass.EditButton();

        setBackground(null);

        jPanel1.setBackground(null);

        roundedPanel3.setBackground(new java.awt.Color(230, 237, 200));

        taskTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        taskTitle.setForeground(new java.awt.Color(60, 74, 61));
        taskTitle.setText(taskname);
        taskTitle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                taskTitleStateChanged(evt);
            }
        });
        taskTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taskTitleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel3Layout = new javax.swing.GroupLayout(roundedPanel3);
        roundedPanel3.setLayout(roundedPanel3Layout);
        roundedPanel3Layout.setHorizontalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(taskTitle)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        roundedPanel3Layout.setVerticalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(taskTitle)
                .addContainerGap())
        );

        buttEditor.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        buttEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttEditorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(buttEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roundedPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttEditorActionPerformed
        if (state == 0) {
            openEDframe();
        }
        else{
            openEDframe();
        }
    }//GEN-LAST:event_buttEditorActionPerformed

    private void taskTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskTitleMouseClicked
        if (evt.getClickCount() == 2) {
            EditTitleFrame newText = new EditTitleFrame(allj, data, this);
            newText.setLocationRelativeTo(null);
            newText.setVisible(true);
            /*
            if (newText.getTextEditor() != null) {
                data.settaskname(newText.getTextEditor());
                System.out.println(newText.getTextEditor());
            }*/
            System.out.println("no."+taskOrder+", name: "+data.gettaskname()+", des.: "+data.getdes()+", d/m/y : "+data.getdmy());
        }
    }//GEN-LAST:event_taskTitleMouseClicked

    private void taskTitleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_taskTitleStateChanged
        if (taskTitle.isSelected()) {
            //data.setstate(1);
            taskTitle.setForeground(new java.awt.Color(187,187,187)); // ????????????
        } else {
            //data.setstate(0);
            taskTitle.setForeground(new java.awt.Color(60, 74, 61)); // ???????????????
        }
    }//GEN-LAST:event_taskTitleStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private decorClass.EditButton buttEditor;
    private javax.swing.JPanel jPanel1;
    private decorClass.RoundedPanel roundedPanel3;
    private static javax.swing.JCheckBox taskTitle;
    // End of variables declaration//GEN-END:variables

}
