/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewSaleAnalysis;

/**
 *
 * @author Admin
 */
public class SaleAnalyticGUIplan extends javax.swing.JFrame {

    /**
     * Creates new form SaleAnalyticGUI
     */
    public SaleAnalyticGUIplan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        SScontainer = new javax.swing.JPanel();
        SaleSumPanel = new javax.swing.JPanel();
        daily = new javax.swing.JPanel();
        incomePanel = new javax.swing.JPanel();
        incomeDisplay = new javax.swing.JLabel();
        BahtPanel = new javax.swing.JPanel();
        bahtLabel = new javax.swing.JLabel();
        incomePanel1 = new javax.swing.JPanel();
        incomeDisplay1 = new javax.swing.JLabel();
        BahtPanel1 = new javax.swing.JPanel();
        bahtLabel1 = new javax.swing.JLabel();
        dailyLpanel = new javax.swing.JPanel();
        bahtLabel2 = new javax.swing.JLabel();
        weekly = new javax.swing.JPanel();
        incomePanel2 = new javax.swing.JPanel();
        incomeDisplay2 = new javax.swing.JLabel();
        BahtPanel2 = new javax.swing.JPanel();
        bahtLabel3 = new javax.swing.JLabel();
        incomePanel3 = new javax.swing.JPanel();
        incomeDisplay3 = new javax.swing.JLabel();
        BahtPanel3 = new javax.swing.JPanel();
        bahtLabel4 = new javax.swing.JLabel();
        weeklyLpanel = new javax.swing.JPanel();
        bahtLabel5 = new javax.swing.JLabel();
        montly = new javax.swing.JPanel();
        incomePanel4 = new javax.swing.JPanel();
        incomeDisplay4 = new javax.swing.JLabel();
        BahtPanel4 = new javax.swing.JPanel();
        bahtLabel6 = new javax.swing.JLabel();
        incomePanel5 = new javax.swing.JPanel();
        incomeDisplay5 = new javax.swing.JLabel();
        BahtPanel5 = new javax.swing.JPanel();
        bahtLabel7 = new javax.swing.JLabel();
        montlyLpanel = new javax.swing.JPanel();
        bahtLabel8 = new javax.swing.JLabel();
        topicPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        topicPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        bestSellerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        topicPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        topicPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        SScontainer.setLayout(new java.awt.BorderLayout());

        SaleSumPanel.setBackground(new java.awt.Color(204, 204, 204));

        daily.setBackground(new java.awt.Color(204, 204, 255));
        daily.setLayout(new java.awt.GridBagLayout());

        incomePanel.setLayout(new java.awt.GridBagLayout());

        incomeDisplay.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        incomeDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incomeDisplay.setText("XXXX.XX");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        incomePanel.add(incomeDisplay, gridBagConstraints);

        bahtLabel.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        bahtLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bahtLabel.setText("Baht");
        BahtPanel.add(bahtLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        incomePanel.add(BahtPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        daily.add(incomePanel, gridBagConstraints);

        incomePanel1.setLayout(new java.awt.GridBagLayout());

        incomeDisplay1.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        incomeDisplay1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incomeDisplay1.setText("XX");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        incomePanel1.add(incomeDisplay1, gridBagConstraints);

        BahtPanel1.setOpaque(false);

        bahtLabel1.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        bahtLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bahtLabel1.setText("Order(s)");
        BahtPanel1.add(bahtLabel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        incomePanel1.add(BahtPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        daily.add(incomePanel1, gridBagConstraints);

        dailyLpanel.setOpaque(false);

        bahtLabel2.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        bahtLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bahtLabel2.setText("Daily");
        dailyLpanel.add(bahtLabel2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        daily.add(dailyLpanel, gridBagConstraints);

        weekly.setBackground(new java.awt.Color(204, 204, 255));
        weekly.setLayout(new java.awt.GridBagLayout());

        incomePanel2.setLayout(new java.awt.GridBagLayout());

        incomeDisplay2.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        incomeDisplay2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incomeDisplay2.setText("XXXX.XX");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        incomePanel2.add(incomeDisplay2, gridBagConstraints);

        bahtLabel3.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        bahtLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bahtLabel3.setText("Baht");
        BahtPanel2.add(bahtLabel3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        incomePanel2.add(BahtPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        weekly.add(incomePanel2, gridBagConstraints);

        incomePanel3.setLayout(new java.awt.GridBagLayout());

        incomeDisplay3.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        incomeDisplay3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incomeDisplay3.setText("XX");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        incomePanel3.add(incomeDisplay3, gridBagConstraints);

        bahtLabel4.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        bahtLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bahtLabel4.setText("Order(s)");
        BahtPanel3.add(bahtLabel4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        incomePanel3.add(BahtPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        weekly.add(incomePanel3, gridBagConstraints);

        weeklyLpanel.setOpaque(false);

        bahtLabel5.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        bahtLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bahtLabel5.setText("Weekly");
        weeklyLpanel.add(bahtLabel5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        weekly.add(weeklyLpanel, gridBagConstraints);

        montly.setBackground(new java.awt.Color(204, 204, 255));
        montly.setLayout(new java.awt.GridBagLayout());

        incomePanel4.setLayout(new java.awt.GridBagLayout());

        incomeDisplay4.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        incomeDisplay4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incomeDisplay4.setText("XXXX.XX");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        incomePanel4.add(incomeDisplay4, gridBagConstraints);

        bahtLabel6.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        bahtLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bahtLabel6.setText("Baht");
        BahtPanel4.add(bahtLabel6);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        incomePanel4.add(BahtPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        montly.add(incomePanel4, gridBagConstraints);

        incomePanel5.setLayout(new java.awt.GridBagLayout());

        incomeDisplay5.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        incomeDisplay5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incomeDisplay5.setText("XX");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        incomePanel5.add(incomeDisplay5, gridBagConstraints);

        bahtLabel7.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        bahtLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bahtLabel7.setText("Order(s)");
        BahtPanel5.add(bahtLabel7);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        incomePanel5.add(BahtPanel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        montly.add(incomePanel5, gridBagConstraints);

        montlyLpanel.setOpaque(false);

        bahtLabel8.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        bahtLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bahtLabel8.setText("Montly");
        montlyLpanel.add(bahtLabel8);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        montly.add(montlyLpanel, gridBagConstraints);

        javax.swing.GroupLayout SaleSumPanelLayout = new javax.swing.GroupLayout(SaleSumPanel);
        SaleSumPanel.setLayout(SaleSumPanelLayout);
        SaleSumPanelLayout.setHorizontalGroup(
            SaleSumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaleSumPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(daily, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(weekly, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(montly, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        SaleSumPanelLayout.setVerticalGroup(
            SaleSumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaleSumPanelLayout.createSequentialGroup()
                .addGroup(SaleSumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(daily, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weekly, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(montly, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        SScontainer.add(SaleSumPanel, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sale Summary");
        topicPanel.add(jLabel1);

        SScontainer.add(topicPanel, java.awt.BorderLayout.PAGE_START);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        topicPanel1.setLayout(flowLayout1);

        jButton1.setText("View Graph");
        topicPanel1.add(jButton1);

        bestSellerPanel.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product Code", "Name", "Quantities"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        bestSellerPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        java.awt.FlowLayout flowLayout4 = new java.awt.FlowLayout();
        flowLayout4.setAlignOnBaseline(true);
        topicPanel2.setLayout(flowLayout4);

        jButton2.setText("View Sale Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        topicPanel2.add(jButton2);

        bestSellerPanel.add(topicPanel2, java.awt.BorderLayout.PAGE_END);

        jLabel2.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Most Selling Products");
        topicPanel3.add(jLabel2);

        bestSellerPanel.add(topicPanel3, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SScontainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(topicPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bestSellerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SScontainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(topicPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bestSellerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new SaleReportGUIplan().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleAnalyticGUIplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleAnalyticGUIplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleAnalyticGUIplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleAnalyticGUIplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SaleAnalyticGUIplan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BahtPanel;
    private javax.swing.JPanel BahtPanel1;
    private javax.swing.JPanel BahtPanel2;
    private javax.swing.JPanel BahtPanel3;
    private javax.swing.JPanel BahtPanel4;
    private javax.swing.JPanel BahtPanel5;
    private javax.swing.JPanel SScontainer;
    private javax.swing.JPanel SaleSumPanel;
    private javax.swing.JLabel bahtLabel;
    private javax.swing.JLabel bahtLabel1;
    private javax.swing.JLabel bahtLabel2;
    private javax.swing.JLabel bahtLabel3;
    private javax.swing.JLabel bahtLabel4;
    private javax.swing.JLabel bahtLabel5;
    private javax.swing.JLabel bahtLabel6;
    private javax.swing.JLabel bahtLabel7;
    private javax.swing.JLabel bahtLabel8;
    private javax.swing.JPanel bestSellerPanel;
    private javax.swing.JPanel daily;
    private javax.swing.JPanel dailyLpanel;
    private javax.swing.JLabel incomeDisplay;
    private javax.swing.JLabel incomeDisplay1;
    private javax.swing.JLabel incomeDisplay2;
    private javax.swing.JLabel incomeDisplay3;
    private javax.swing.JLabel incomeDisplay4;
    private javax.swing.JLabel incomeDisplay5;
    private javax.swing.JPanel incomePanel;
    private javax.swing.JPanel incomePanel1;
    private javax.swing.JPanel incomePanel2;
    private javax.swing.JPanel incomePanel3;
    private javax.swing.JPanel incomePanel4;
    private javax.swing.JPanel incomePanel5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel montly;
    private javax.swing.JPanel montlyLpanel;
    private javax.swing.JPanel topicPanel;
    private javax.swing.JPanel topicPanel1;
    private javax.swing.JPanel topicPanel2;
    private javax.swing.JPanel topicPanel3;
    private javax.swing.JPanel weekly;
    private javax.swing.JPanel weeklyLpanel;
    // End of variables declaration//GEN-END:variables
}
