/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewSaleAnalysis;

/**
 *
 * @author Admin
 */
public class SaleReportGUIplan extends javax.swing.JFrame {

    /**
     * Creates new form SaleAnalyticGUI
     */
    public SaleReportGUIplan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        SScontainer = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        enterdatePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        startDate = new javax.swing.JLabel();
        startDateTextField = new javax.swing.JTextField();
        endDate = new javax.swing.JLabel();
        endDateTextField = new javax.swing.JTextField();
        displayButtonPanel = new javax.swing.JPanel();
        confirmBPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        displayAllBPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        topicPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bestSellerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        SScontainer.setLayout(new java.awt.BorderLayout());

        searchPanel.setBackground(new java.awt.Color(204, 204, 204));
        searchPanel.setLayout(new java.awt.GridLayout(2, 1));

        enterdatePanel.setLayout(new java.awt.GridLayout(2, 1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("enter dd/mm/yyyy for specific sale reports");
        enterdatePanel.add(jLabel2);

        startDate.setText("start date");
        jPanel1.add(startDate);

        startDateTextField.setPreferredSize(new java.awt.Dimension(120, 22));
        startDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(startDateTextField);

        endDate.setText("end date");
        jPanel1.add(endDate);

        endDateTextField.setPreferredSize(new java.awt.Dimension(120, 22));
        endDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endDateTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(endDateTextField);

        enterdatePanel.add(jPanel1);

        searchPanel.add(enterdatePanel);

        displayButtonPanel.setPreferredSize(new java.awt.Dimension(452, 22));
        displayButtonPanel.setLayout(new java.awt.GridLayout(2, 1));

        jButton2.setText("confirm");
        confirmBPanel.add(jButton2);

        displayButtonPanel.add(confirmBPanel);

        jButton3.setText("display all sale reports");
        displayAllBPanel1.add(jButton3);

        displayButtonPanel.add(displayAllBPanel1);

        searchPanel.add(displayButtonPanel);

        SScontainer.add(searchPanel, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sale Reports");
        topicPanel.add(jLabel1);

        SScontainer.add(topicPanel, java.awt.BorderLayout.PAGE_START);

        bestSellerPanel.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product Code", "Name", "Quantities"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        bestSellerPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SScontainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bestSellerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SScontainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bestSellerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDateTextFieldActionPerformed

    private void endDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endDateTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleReportGUIplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleReportGUIplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleReportGUIplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleReportGUIplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SaleReportGUIplan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SScontainer;
    private javax.swing.JPanel bestSellerPanel;
    private javax.swing.JPanel confirmBPanel;
    private javax.swing.JPanel displayAllBPanel1;
    private javax.swing.JPanel displayButtonPanel;
    private javax.swing.JLabel endDate;
    private javax.swing.JTextField endDateTextField;
    private javax.swing.JPanel enterdatePanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel startDate;
    private javax.swing.JTextField startDateTextField;
    private javax.swing.JPanel topicPanel;
    // End of variables declaration//GEN-END:variables
}
